[package]
name = "matty"
version = "0.1.0"
edition = "2024"

[dependencies]
material-colors = { version = "=0.4.2", features = ["image", "serde"] }
serde = "1.0.219"
serde_json = "1.0.140"
sha2 = "0.10.9"
