[package]
name = "matty"
version = "0.1.0"
edition = "2024"

[dependencies]
material-colors = { version = "=0.4.2", features = ["image"] }
sha2 = { version = "0.10.9", features = ["asm"] }

[profile.release-with-debug]
inherits = "release"
debug = true
